services:
  main:
    container_name: main
    build:
      context: .
      dockerfile: ./build/main.Dockerfile
    env_file:
      - .env
    environment:
      - STORAGE=${STORAGE}
    depends_on:
      postgres:
        condition: service_started
    restart: always
    ports:
      - "8080:8080"
      - "9090:9090"
    networks:
      - Ozon_test-network
  postgres:
    env_file:
      - .env
    container_name: postgres
    image: postgres:15.0
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - Ozon_test-network
    volumes:
      - ./build/sql/create_script.sql:/docker-entrypoint-initdb.d/initdb.sql
      - Ozon_test-db-data:/var/lib/postgresql/data
networks:
  Ozon_test-network:
    name: Ozon_test-network
    driver: bridge
volumes:
  Ozon_test-db-data:
