services:
  main:
    container_name: main
    build:
      context: .
      dockerfile: ./build/main.Dockerfile
    env_file:
      - .env
    environment:
      - STORAGE=${STORAGE}
    restart: always
    ports:
      - "8080:8080"
      - "9090:9090"
    networks:
      - Ozon_test-network

networks:
  Ozon_test-network:
    name: Ozon_test-network
    driver: bridge

volumes:
  Ozon_test-db-data:
